In [ ]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [2]:
import numpy as np
import pandas as pd

**Importing the dataset**

In [4]:
df = pd.read_csv("Social_Network_Ads.csv")

In [5]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

**Splitting the dataset into the Training set and Test set**

In [6]:
#first splitting the data set into independent and dependent data
x=df.iloc[:,[2,3]].values
y=df.iloc[:,4].values

In [7]:
x[:5]

array([[   19, 19000],
       [   35, 20000],
       [   26, 43000],
       [   27, 57000],
       [   19, 76000]])

In [8]:
y[:5]

array([0, 0, 0, 0, 0])

In [9]:
#now splittng this dependent and independent data into training and test set

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.25, random_state=None)

In [10]:
x_train[:5]

array([[    43, 133000],
       [    41,  72000],
       [    29,  43000],
       [    22,  18000],
       [    39,  42000]])

In [12]:
x_test[:5]

array([[    26,  15000],
       [    25,  80000],
       [    20,  74000],
       [    38,  61000],
       [    59, 130000]])

**Feature Scaling**

In [26]:
#scaling only the independent variables as dependent are already in 0 and 1 format(binary)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
x_train[:5]

array([[ 0.49837523,  1.93673644],
       [ 0.30935808,  0.10006355],
       [-0.82474485, -0.77310882],
       [-1.4863049 , -1.52584361],
       [ 0.12034092, -0.80321821]])

In [15]:
x_test[:5]

array([[-1.12981717, -1.59716999],
       [-1.22857741,  0.19461547],
       [-1.72237862,  0.02921989],
       [ 0.05530574, -0.3291372 ],
       [ 2.12927082,  1.57291197]])

**Fitting K-NN to the Training set**

In [21]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5, p=2, metric='minkowski')

knn.fit(x_train,y_train)

KNeighborsClassifier()

**Predicting the Test set results**

In [23]:
y_pred=knn.predict(x_test)

**Making the Confusion Matrix**

In [24]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)

In [25]:
cm

array([[59,  3],
       [ 5, 33]])

92 predictions are correct whereas 8 are wrong